### PR TITLE
Development

### PR DESCRIPTION
**Pull request by risingworld777**
OAuth implementation

### CODE REVIEW

**Comment by sisimma** [comment]
I'm a novice about OAuth. I just built a webpage for my app temporarily at godaddy and put the web page in redirect url menu of OAuth tab in my developed app in my alpaca account. I didn't set anything in creating app except changing my app name as 'sisimtrade' instead of 'alpaca' in string.xml. 
I have several questions now:
1. Are you asking how I set redirect url when creat app because I should have set 'redirect url' somewhere correctly? (if so, could you tell me how?)
2. attached is a screenshot of OAuth tab in my alpaca account. 
- is the right place and right redirect url? (what is the redirect url? how do I make it?)
- I also emailed alpaca by clicking a link in the screeshot to get approved as an app. not sure if I'm right. could you tell me?

my-developed-app

Thanks in advance

**Comment by risingworld777** [comment]
@sisimma The redirect url should be `alpacamobile://oauth`. 
But it's not allowed to input in that way right now. I will let you know after fix this issue.
Also I will update readme file.
Thanks.

**Comment by sisimma** [comment]
looking forward to seeing your update. really appreciate it.

**Comment by risingworld777** [comment]
@sisimma  The issue should be fixed now.

**Comment by sisimma** [comment]
I set redirect url as you mentioned alpacamobile://oauth.
However the app shows the same symptom as before. 
1. launch an app
2. it shows "Authenticate with Alpaca"
3. click on it
4. opens a browser and goes to app.alpaca.markets on browser.
5. I log in with my login credential
6. it shows "logged in successfully" and a page having two buttons 'Deny' and 'Allow' for "Authorize Alpaca Mobile".
7. pressing button either on 'Deny' or 'Allow' goes back to the app showing a button "Authenticate with Alpaca".
8. click it. then goes to number 4 above. (keep iterating step 4 through step 8 forever)

could you explain what would be a cause and how to resolve this?

thank you in advance.
Sukhwan,

**Comment by risingworld777** [comment]
@sisimma  It seems you are not getting `access_token`. Can you debug what is returning when call `exchangeTokenAttempt` saga func?
If you can't, please share your client id/secret.

**Comment by sisimma** [comment]
don't I need to get any approval from Alpaca? Is it good enough for my app
to run as long as I have client id and client secret?

here are the client id and client secret:
 AUTH_CLIENT_ID: 'bef73dfa5fa25adf04d61e787b887d38',
 AUTH_CLIENT_SECRET: 'd70b19b7ee5defdb7ae28cc7c65c5ccc9a066f4f',

could you tell where the file path to debug and how to print the return
value if you don't mind?

Thanks.

**Comment by risingworld777** [comment]
`exchangeTokenAttempt` func of `AppSaga.js`

**Comment by sisimma** [comment]
I added more Console log into AppSaga.js. how to apply this change in
build? I'm using Android studio project by opening alpaca-rn-mobile\android
folder. But it doesn't seem to have the change outside of android applied
in building apk.
could you help?
Thanks.

**Comment by sisimma** [comment]
any update for my issue?

**Comment by risingworld777** [comment]
Sorry for getting back to you lately. 
I tested with your id/secret and it works fine in my side. (Remove above id/secret)
Which android phone are you using?

**Comment by sisimma** [comment]
samsung s10Plus.
could you send the apk to me so that I can install and try it? if it works then, my environment is not set correctly. my email is sisimma@ gmail . com
thanks.

**Comment by risingworld777** [comment]
`react-native run-android`:  It runs debug apk built with current code on your phone.
`adb install xxx.apk`: It seems you have installed old apk built previously by this command.
You should use `react-native run-android`

**Comment by sisimma** [comment]
Let me ask in different way. Previously I built the project in android studio. and then installed an apk in android/app/build/output/apk/debug/app-degug.apk. Now I'm doing build and run using 'react-native run-android'. Could you tell me why the apk built using android studio not working while 'react-native run-android works? I wonder what is difference?

**Comment by risingworld777** [comment]
There is other command to build debug or release apk.
`react-native run-android`: This command builds the project and runs apk on phone without creating apk.

**Pull request merged**
